export const northern = [
  "Hoà Bình",
  "Sơn La",
  "Điện Biên",
  "Lai Châu",
  "Lào Cai",
  "Hà Giang Cao Bằng",
  "Bắc Kạn",
  "Yên Bái",
  "Lạng Sơn",
  "Tuyên Quang",
  "Thái Nguyên",
  "Phú Thọ",
  "Bắc Giang",
  "Quảng Ninh",
  "Hà Nội",
  "Hải Phòng",
  "Vĩnh Phúc",
  "Bắc Ninh",
  "Hà Nam",
  "Hải Dương",
  "Hưng Yên",
  "Nam Định",
  "Ninh Bình",
  "Thái Bình",
];

export const central = [
  "Thanh Hoá",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Thừa Thiên-Huế",
  "Tp Đà Đẵng",
  "Quảng Nam",
  "Quảng Ngãi",
  "Bình Định",
  "Phú Yên",
  "Khánh Hoà",
  "Ninh Thuận",
  "Bình Thuận",
  "Kon Tum",
  "Gia Lai",
  "Đắc Lắc",
  "Đắc Nông",
  "Lâm Đồng",
];

export const south = [
  "Bình Phước",
  "Bình Dương",
  "Đồng Nai",
  "Tây Ninh",
  "Bà Rịa-Vũng Tàu",
  "Thành phố Hồ Chí Minh",
  "Long An",
  "Đồng Tháp",
  "Tiền Giang",
  "An Giang",
  "Bến Tre",
  "Vĩnh Long",
  "Trà Vinh",
  "Hậu Giang",
  "Kiên Giang",
  "Sóc Trăng",
  "Bạc Liêu",
  "Cà Mau",
  "Thành phố Cần Thơ",
];
